import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth } = Dimensions.get("window");
const CROP_SIZE = 300;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9F1EA",
    padding: 20,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#8B4513",
    marginBottom: 20,
    textAlign: "center",
  },
  categoryPicker: {
    height: 48,
    borderColor: "#8B4513",
    borderWidth: 1.5,
    borderRadius: 10,
    marginBottom: 20,
    backgroundColor: "#FFFFFF",
    color: "#333333",
    paddingHorizontal: 10,
  },
  searchInput: {
    height: 48,
    borderColor: "#8B4513",
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 16,
    marginBottom: 20,
    backgroundColor: "#FFFFFF",
    color: "#333333",
    fontSize: 16,
  },
  productList: {
    paddingBottom: 20,
  },
  productItem: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    marginVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D9C2A6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  selectedProductItem: {
    borderColor: "#8B4513",
    borderWidth: 2,
    backgroundColor: "#FFE8D6",
  },
  productText: {
    fontSize: 18,
    color: "#333333",
    fontWeight: "600",
  },
  productCode: {
    fontSize: 14,
    color: "#666666",
    marginTop: 6,
  },
  categoryText: {
    fontSize: 14,
    color: "#666666",
    marginTop: 6,
  },
  emptyText: {
    fontSize: 18,
    color: "#666666",
    textAlign: "center",
    marginTop: 24,
  },
  loading: {
    marginTop: 24,
  },
  uploadSection: {
    marginTop: 20,
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D9C2A6",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  selectedProductText: {
    fontSize: 18,
    color: "#8B4513",
    fontWeight: "600",
    marginBottom: 16,
    textAlign: "center",
  },
  productImage: {
    width: 100,
    height: 100,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#D9C2A6",
  },
  imagePlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: "#D9C2A6",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  placeholderText: {
    fontSize: 14,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
    width: "100%",
  },
  uploadButton: {
    backgroundColor: "#8B4513",
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 10,
    minWidth: 120,
  },
  deleteButton: {
    backgroundColor: "#C62828",
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 10,
    minWidth: 120,
  },
  uploadButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  deleteButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  disabledButton: {
    backgroundColor: "#A9A9A9",
    opacity: 0.7,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  previewContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 20,
    width: "90%",
    maxWidth: 400,
    alignItems: "center",
  },
  cropContainer: {
    width: CROP_SIZE,
    height: CROP_SIZE,
    overflow: "hidden",
    position: "relative",
    marginBottom: 20,
  },
  previewImage: {
    width: CROP_SIZE,
    height: CROP_SIZE,
    position: "absolute",
  },
  cropOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  cropFrame: {
    width: CROP_SIZE,
    height: CROP_SIZE,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    backgroundColor: "transparent",
  },
  modalButtonContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
    width: "100%",
  },
  modalButton: {
    backgroundColor: "#8B4513",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    minWidth: 100,
  },
  modalButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
});

export default styles;