import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FDF6E3",
    paddingTop: 50,
  },
  topNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "linear-gradient(90deg, #F28C38 0%, #4A704A 100%)",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    width: "100%",
    paddingHorizontal: 20,
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: Platform.OS === "android" ? 4 : 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  navItem: {
    alignItems: "center",
    paddingVertical: 6,
  },
  navText: {
    fontSize: 10,
    color: "#3D2C29",
    marginTop: 3,
    fontWeight: "600",
  },
  categoryContainer: {
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    paddingVertical: 10,
    marginTop: 10,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: Platform.OS === "android" ? 2 : 0,
  },
  categoryList: {
    paddingHorizontal: 10,
  },
  categoryItem: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginRight: 10,
    transform: [{ scale: 1 }],
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: Platform.OS === "android" ? 1 : 0,
  },
  categoryItemSelected: {
    backgroundColor: "#F28C38",
    borderColor: "#F28C38",
    transform: [{ scale: 1.05 }],
  },
  categoryText: {
    fontSize: 14,
    color: "#3D2C29",
    marginTop: 3,
    textAlign: "center",
    fontWeight: "500",
  },
  categoryTextSelected: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  categoryCount: {
    fontSize: 12,
    color: "#6B5E4A",
    marginTop: 2,
  },
  categoryCountSelected: {
    color: "#FFFFFF",
  },
  productContainer: {
    paddingVertical: 10,
    paddingHorizontal: 5,
  },
  productCard: {
    flex: 1,
    backgroundColor: "linear-gradient(135deg, #FFFFFF 0%, #FDF6E3 100%)",
    borderRadius: 15,
    padding: 12,
    margin: 5,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: Platform.OS === "android" ? 3 : 0,
    maxWidth: (width - 40) / 2,
    transform: [{ scale: 1 }],
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
    marginBottom: 10,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  productImagePlaceholder: {
    width: 80,
    height: 80,
    backgroundColor: "#E8ECEF",
    borderRadius: 12,
    marginBottom: 10,
    marginTop: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D0D5DD",
  },
  placeholderText: {
    fontSize: 12,
    color: "#6B5E4A",
    fontStyle: "italic",
  },
  productName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#3D2C29",
    textAlign: "center",
    marginBottom: 5,
  },
  productPrice: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#4A704A",
    backgroundColor: "rgba(74, 112, 74, 0.1)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginBottom: 5,
  },
  quantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  quantityButton: {
    backgroundColor: "linear-gradient(90deg, #F28C38 0%, #E07B2E 100%)",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginHorizontal: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: Platform.OS === "android" ? 2 : 0,
    borderWidth: 0,
  },
  quantityButtonText: {
    color: "#000000",
    fontSize: 12,
    fontWeight: "600",
  },
  quantityText: {
    fontSize: 14,
    color: "#3D2C29",
    marginHorizontal: 5,
  },
  removeButton: {
    backgroundColor: "linear-gradient(90deg, #D9534F 0%, #C9302C 100%)",
    borderWidth: 0,
  },
  cartItem: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginBottom: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: Platform.OS === "android" ? 2 : 0,
  },
  cartItemName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#3D2C29",
    width: "100%",
    marginBottom: 5,
  },
  cartItemPrice: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#4A704A",
  },
  quantityControl: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  cartModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    padding: 15,
    width: "90%",
    maxHeight: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: Platform.OS === "android" ? 5 : 0,
  },
  qrModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    padding: 15,
    width: "80%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: Platform.OS === "android" ? 5 : 0,
  },
  qrCodeContainer: {
    marginVertical: 20,
    padding: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  cartTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#3D2C29",
    textAlign: "center",
    marginBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: "#F28C38",
    paddingBottom: 5,
  },
  cartList: {
    paddingBottom: 10,
  },
  cartTotal: {
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    alignItems: "center",
  },
  cartTotalText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#4A704A",
  },
  loading: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -25 }, { translateY: -25 }],
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 20,
    marginHorizontal: 5,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: Platform.OS === "android" ? 2 : 0,
  },
  errorText: {
    fontSize: 14,
    color: "#D9534F",
    textAlign: "center",
    marginBottom: 10,
    fontWeight: "500",
  },
  retryButton: {
    backgroundColor: "linear-gradient(90deg, #F28C38 0%, #E07B2E 100%)",
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: Platform.OS === "android" ? 2 : 0,
    borderWidth: 0,
  },
  retryButtonText: {
    fontSize: 14,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  noDataText: {
    fontSize: 14,
    color: "#6B5E4A",
    textAlign: "center",
    marginVertical: 15,
    marginHorizontal: 5,
    fontStyle: "italic",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  previewContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    padding: 15,
    width: "80%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: Platform.OS === "android" ? 5 : 0,
  },
  previewImage: {
    width: "100%",
    height: 300,
    borderRadius: 10,
    marginBottom: 15,
  },
  modalButton: {
    backgroundColor: "linear-gradient(90deg, #F28C38 0%, #E07B2E 100%)",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: Platform.OS === "android" ? 2 : 0,
    borderWidth: 0,
    marginVertical: 5,
  },
  closeCartButton: {
    backgroundColor: "#D32F2F",
  },
  clearCartButton: {
    backgroundColor: "#D9534F",
  },
  qrButton: {
    backgroundColor: "#4A704A", // Dark green for QR button
  },
  modalButtonText: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  animatedImageContainer: {
    position: "absolute",
    zIndex: 1000,
  },
  animatedImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
});

export default styles;