import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF",
    marginHorizontal: 10,
    marginTop: 15, // Added top margin
    marginBottom: 20,
  },
  header: {
    backgroundColor: "#A0522D",
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 10,
  },
  title: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
  },
  headerButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
  },
  backButtonText: {
    color: "#FFF",
    fontSize: 14,
    marginLeft: 6,
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
  },
  filterButtonText: {
    color: "#FFF",
    fontSize: 14,
    marginLeft: 6,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
  reportHeader: {
    alignItems: "center",
    marginBottom: 20,
  },
  reportDate: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#A0522D",
    marginBottom: 6,
    textAlign: "center",
  },
  reportPrinted: {
    fontSize: 12,
    color: "#666",
  },
  tableContainer: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 4,
    marginHorizontal: 4,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#D3D3D3",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    marginBottom: 8,
  },
  headerCell: {
    fontWeight: "bold",
    fontSize: 8,
    textAlign: "center",
    paddingHorizontal: 4,
    flexShrink: 1,
  },
  reportRow: {
    flexDirection: "row",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  reportCell: {
    fontSize: 8,
    textAlign: "center",
    paddingHorizontal: 4,
    flexShrink: 1,
    overflow: "hidden",
  },
  reportList: {
    paddingBottom: 20,
    paddingHorizontal: 4,
  },
  noDataText: {
    textAlign: "center",
    marginTop: 20,
    fontSize: 14,
    color: "#666",
    paddingHorizontal: 16,
  },
  loading: {
    marginTop: 20,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  errorText: {
    fontSize: 14,
    color: "#D32F2F",
    textAlign: "center",
    marginBottom: 8,
  },
  retryButton: {
    backgroundColor: "#A0522D",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 4,
  },
  retryButtonText: {
    color: "#FFF",
    fontSize: 12,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "#FFF",
    marginHorizontal: 20,
    padding: 16,
    borderRadius: 8,
    alignItems: "center",
    maxWidth: 340,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 12,
    color: "#A0522D",
  },
  optionContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    width: "100%",
  },
  optionButton: {
    flex: 1,
    padding: 8,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: "#A0522D",
    borderRadius: 4,
    alignItems: "center",
  },
  selectedOption: {
    backgroundColor: "#A0522D",
  },
  optionText: {
    color: "#A0522D",
    fontSize: 12,
  },
  selectedOptionText: {
    color: "#FFF",
    fontSize: 12,
  },
  datePickerButton: {
    padding: 8,
    borderWidth: 1,
    borderColor: "#A0522D",
    borderRadius: 4,
    backgroundColor: "#F9F9F9",
    marginVertical: 6,
    width: "100%",
  },
  datePickerText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#A0522D",
    textAlign: "center",
  },
  datePickerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 12,
  },
  customPicker: {
    flex: 1,
    marginHorizontal: 4,
    padding: 8,
    borderWidth: 1,
    borderColor: "#A0522D",
    borderRadius: 4,
    backgroundColor: "#F9F9F9",
    alignItems: "center",
  },
  customPickerText: {
    fontSize: 14,
    color: "#000",
  },
  pickerOption: {
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  pickerOptionText: {
    fontSize: 14,
    color: "#000",
    textAlign: "center",
  },
  pickerList: {
    maxHeight: 180,
    width: "100%",
  },
  datePreview: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#A0522D",
    marginBottom: 12,
    textAlign: "center",
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#D32F2F",
    padding: 8,
    borderRadius: 4,
    alignItems: "center",
    marginRight: 4,
  },
  cancelButtonText: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "600",
  },
  confirmButton: {
    flex: 1,
    backgroundColor: "#A0522D",
    padding: 8,
    borderRadius: 4,
    alignItems: "center",
    marginLeft: 4,
  },
  confirmButtonText: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "600",
  },
});
