import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "rgba(0, 206, 209, 0.2)", // Light turquoise background
    paddingHorizontal: 15,
    paddingTop: 40, // Space for status bar
    paddingBottom: 40, // Space at bottom
  },
  header: {
    backgroundColor: "#00CED1", // Turquoise header
    borderRadius: 8,
    marginBottom: 15,
    marginTop: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: "#00CED1",
    marginTop: 10,
  },
  backButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 6,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FF69B4", // Pink text
    textAlign: "center",
    paddingVertical: 4,
    marginTop: 10,
    flex: 1,
  },
  contentContainer: {
    marginVertical: 15,
    marginTop: 20,
  },
  categoryItem: {
    backgroundColor: "#00CED1",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginVertical: 8,
    marginTop: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  categoryText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FF69B4",
    textAlign: "center",
  },
  productItem: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginVertical: 8,
    marginTop: 10,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 2,
    borderColor: "#00CED1",
  },
  productText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FF69B4",
    marginBottom: 8,
  },
  quantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
  },
  quantityButton: {
    backgroundColor: "#00CED1",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginHorizontal: 5,
  },
  quantityButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  quantityText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1A1A1A",
    marginHorizontal: 10,
  },
  addButton: {
    backgroundColor: "#FF69B4",
    paddingVertical: 6,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginLeft: 10,
  },
  addButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  cartItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginVertical: 8,
    marginTop: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    borderWidth: 2,
    borderColor: "#00CED1",
  },
  cartItemText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FF69B4",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 20,
    marginTop: 30,
  },
  errorText: {
    fontSize: 16,
    color: "#D32F2F",
    marginBottom: 10,
  },
  retryButton: {
    backgroundColor: "#00CED1",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginVertical: 10,
    marginTop: 15,
  },
  retryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  input: {
    width: 200,
    height: 40,
    borderColor: "#00CED1",
    borderWidth: 2,
    borderRadius: 10,
    marginVertical: 10,
    marginTop: 15,
    paddingHorizontal: 10,
    backgroundColor: "#FFFFFF",
    color: "#1A1A1A",
  },
  list: {
    paddingHorizontal: 0,
    paddingBottom: 20,
    paddingTop: 10,
  },
  cartList: {
    paddingHorizontal: 0,
    paddingBottom: 20,
    paddingTop: 10,
  },
  productList: {
    paddingHorizontal: 0,
    paddingBottom: 30,
    paddingTop: 10,
  },
  cartHeader: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FF69B4",
    textAlign: "center",
    paddingVertical: 8,
    marginTop: 5,
  },
  noDataText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FF69B4",
    textAlign: "center",
    marginVertical: 20,
    marginTop: 25,
  },
  checkoutButton: {
    backgroundColor: "#FF69B4",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginVertical: 10,
    marginTop: 15,
    alignItems: "center",
  },
  checkoutButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  viewCartButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF69B4",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginVertical: 10,
    marginTop: 15,
  },
  viewCartButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
  scanQRButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#00CED1", // Turquoise for QR button
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginVertical: 10,
    marginTop: 5, // Slightly less margin to align with viewCartButton
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  scanQRButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
  clearCartButton: {
    backgroundColor: "#D32F2F",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginVertical: 10,
    marginTop: 15,
    alignItems: "center",
  },
  clearCartButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  optionContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 10,
    marginTop: 15,
  },
  optionButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#00CED1",
    marginHorizontal: 5,
  },
  selectedOption: {
    backgroundColor: "#00CED1",
  },
  optionText: {
    fontSize: 14,
    color: "#1A1A1A",
  },
  selectedOptionText: {
    fontSize: 14,
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  confirmButton: {
    backgroundColor: "#00CED1",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginHorizontal: 10,
    marginTop: 15,
  },
  confirmButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  cancelButton: {
    backgroundColor: "#D32F2F",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginHorizontal: 10,
    marginTop: 15,
  },
  cancelButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  loading: {
    flex: 1,
    justifyContent: "center",
    marginTop: 30,
  },
  cartSummary: {
    padding: 10,
    backgroundColor: "#00CED1",
    borderRadius: 8,
    marginVertical: 10,
    marginTop: 15,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 10,
    width: "80%",
    alignItems: "center",
    elevation: 5,
    marginTop: 20,
  },
  receiptModalContent: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 10,
    width: "80%",
    alignItems: "center",
    elevation: 5,
    marginTop: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 15,
    marginTop: 10,
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  applyButton: {
    backgroundColor: "#FF69B4",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginVertical: 10,
    marginTop: 15,
  },
  applyButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  summaryText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1A1A1A",
    marginVertical: 5,
    marginTop: 10,
  },
  receiptText: {
    fontSize: 14,
    color: "#1A1A1A",
    marginBottom: 15,
    marginTop: 10,
    fontFamily: "monospace",
    textAlign: "left",
  },
  qrScannerContainer: {
    flex: 1,
    backgroundColor: "#000000",
    justifyContent: "center",
    alignItems: "center",
  },
  qrCamera: {
    flex: 1,
    width: "100%",
  },
  qrOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  qrFrame: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: "#00CED1",
    borderRadius: 10,
    backgroundColor: "transparent",
  },
  closeQRButton: {
    backgroundColor: "#FF69B4", // Pink for close button
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginVertical: 20,
    marginBottom: 30,
    alignItems: "center",
  },
  closeQRButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
});

export default styles;